Fix import on machines that lack a fully qualified domain name
Some machines do not have fully qualified domain names, and
therefore `socket.gethostbyname(socket.gethostname())` fails,
making it impossible to import `dl.queryClient`.

For example, on my NASA-managed MacBook, I get this error:

    >>> import socket
    >>> socket.gethostbyname(socket.gethostname())
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    socket.gaierror: [Errno 8] nodename nor servname provided, or not known

Instead, look up the host's IP address using the method suggested in
https://stackoverflow.com/questions/166506#answer-28950776 of
opening a datagram socket to a test IP address. We use one of the
addresses from RFC 5737 "IPv4 Address Blocks Reserved for Documentation"
so that we don't actually connect to a real IP address.